-- GENERATED by scripts/gen-promotion-parity.mjs — do not edit.
-- Source of truth: packages/domain/src/promotion.cases.json
--
-- Runs the shared promotion fixture through the Postgres evaluator. The same
-- cases run through the TypeScript evaluator in
-- packages/domain/src/promotion.parity.test.ts. Both must agree: the engine
-- decides which children move up a year, and an implementation that disagrees
-- with itself is worse than one that is simply wrong, because it is wrong only
-- sometimes.
--
-- 16 cases.

create temp table if not exists promo_parity(
  case_name text, facts jsonb, expected text, actual text, verdict text);
truncate promo_parity;

insert into promo_parity (case_name, facts, expected) values
  ('"clear pass promotes"'::jsonb::text, '{"aggregate":55,"credit_count":0,"pass_count":0,"pass_count_principal":0,"pass_count_subsidiary":0,"attendance_pct":90,"attendance_pct_incl_authorised":95,"times_repeated":0,"age_at_jan_1":15,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":8,"stream":null}'::jsonb, '"promote"'::jsonb::text),
  ('"boundary aggregate is inclusive"'::jsonb::text, '{"aggregate":40,"credit_count":0,"pass_count":0,"pass_count_principal":0,"pass_count_subsidiary":0,"attendance_pct":90,"attendance_pct_incl_authorised":95,"times_repeated":0,"age_at_jan_1":15,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":8,"stream":null}'::jsonb, '"promote"'::jsonb::text),
  ('"just under the boundary does not promote"'::jsonb::text, '{"aggregate":39.99,"credit_count":0,"pass_count":0,"pass_count_principal":0,"pass_count_subsidiary":0,"attendance_pct":90,"attendance_pct_incl_authorised":95,"times_repeated":3,"age_at_jan_1":15,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":8,"stream":null}'::jsonb, '"repeat"'::jsonb::text),
  ('"second-attempt relief for a near miss who attended"'::jsonb::text, '{"aggregate":37,"credit_count":0,"pass_count":0,"pass_count_principal":0,"pass_count_subsidiary":0,"attendance_pct":90,"attendance_pct_incl_authorised":80,"times_repeated":1,"age_at_jan_1":15,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":8,"stream":null}'::jsonb, '"conditional_promote"'::jsonb::text),
  ('"no relief after two repeats"'::jsonb::text, '{"aggregate":37,"credit_count":0,"pass_count":0,"pass_count_principal":0,"pass_count_subsidiary":0,"attendance_pct":90,"attendance_pct_incl_authorised":95,"times_repeated":2,"age_at_jan_1":15,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":8,"stream":null}'::jsonb, '"repeat"'::jsonb::text),
  ('"no relief on poor attendance"'::jsonb::text, '{"aggregate":38,"credit_count":0,"pass_count":0,"pass_count_principal":0,"pass_count_subsidiary":0,"attendance_pct":90,"attendance_pct_incl_authorised":60,"times_repeated":0,"age_at_jan_1":15,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":8,"stream":null}'::jsonb, '"repeat"'::jsonb::text),
  ('"a pupil with no marks does not promote on a null aggregate"'::jsonb::text, '{"aggregate":null,"credit_count":0,"pass_count":0,"pass_count_principal":0,"pass_count_subsidiary":0,"attendance_pct":90,"attendance_pct_incl_authorised":99,"times_repeated":0,"age_at_jan_1":15,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":8,"stream":null}'::jsonb, '"repeat"'::jsonb::text),
  ('"Lower VI entry on four credits"'::jsonb::text, '{"aggregate":null,"credit_count":4,"pass_count":0,"pass_count_principal":0,"pass_count_subsidiary":0,"attendance_pct":90,"attendance_pct_incl_authorised":95,"times_repeated":0,"age_at_jan_1":15,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":11,"stream":null}'::jsonb, '"promote"'::jsonb::text),
  ('"three credits with age relief goes up conditionally"'::jsonb::text, '{"aggregate":null,"credit_count":3,"pass_count":0,"pass_count_principal":0,"pass_count_subsidiary":0,"attendance_pct":90,"attendance_pct_incl_authorised":95,"times_repeated":1,"age_at_jan_1":18,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":11,"stream":null}'::jsonb, '"conditional_promote"'::jsonb::text),
  ('"three credits, already repeated, too old — leaves after SC"'::jsonb::text, '{"aggregate":null,"credit_count":3,"pass_count":0,"pass_count_principal":0,"pass_count_subsidiary":0,"attendance_pct":90,"attendance_pct_incl_authorised":95,"times_repeated":2,"age_at_jan_1":21,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":11,"stream":null}'::jsonb, '"leave"'::jsonb::text),
  ('"two credits, never repeated — repeats Form V"'::jsonb::text, '{"aggregate":null,"credit_count":2,"pass_count":0,"pass_count_principal":0,"pass_count_subsidiary":0,"attendance_pct":90,"attendance_pct_incl_authorised":95,"times_repeated":0,"age_at_jan_1":15,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":11,"stream":null}'::jsonb, '"repeat"'::jsonb::text),
  ('"Upper VI entry on two Principal and two Subsidiary"'::jsonb::text, '{"aggregate":null,"credit_count":0,"pass_count":0,"pass_count_principal":2,"pass_count_subsidiary":2,"attendance_pct":90,"attendance_pct_incl_authorised":95,"times_repeated":0,"age_at_jan_1":15,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":12,"stream":null}'::jsonb, '"promote"'::jsonb::text),
  ('"three Principal but one Subsidiary is not enough"'::jsonb::text, '{"aggregate":null,"credit_count":0,"pass_count":0,"pass_count_principal":3,"pass_count_subsidiary":1,"attendance_pct":90,"attendance_pct_incl_authorised":95,"times_repeated":0,"age_at_jan_1":15,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":12,"stream":null}'::jsonb, '"repeat"'::jsonb::text),
  ('"cannot qualify and cannot repeat — referred, not failed"'::jsonb::text, '{"aggregate":null,"credit_count":0,"pass_count":0,"pass_count_principal":0,"pass_count_subsidiary":0,"attendance_pct":90,"attendance_pct_incl_authorised":95,"times_repeated":1,"age_at_jan_1":15,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":12,"stream":null}'::jsonb, '"refer"'::jsonb::text),
  ('"Upper VI completes school; the outcome is leaving"'::jsonb::text, '{"aggregate":80,"credit_count":0,"pass_count":0,"pass_count_principal":0,"pass_count_subsidiary":0,"attendance_pct":90,"attendance_pct_incl_authorised":95,"times_repeated":0,"age_at_jan_1":15,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":13,"stream":null}'::jsonb, '"leave"'::jsonb::text),
  ('"a grade with no rules at all falls through to repeat"'::jsonb::text, '{"aggregate":99,"credit_count":0,"pass_count":0,"pass_count_principal":0,"pass_count_subsidiary":0,"attendance_pct":90,"attendance_pct_incl_authorised":95,"times_repeated":0,"age_at_jan_1":15,"has_medical_certificate_for_prolonged_absence":false,"core_passed":{},"grade":6,"stream":null}'::jsonb, '"repeat"'::jsonb::text);

-- Evaluate each fixture against the seeded rules for the demo school's active
-- year, which app.seed_promotion_rules populated.
do $$
declare
  v_year uuid; c record; r record; cond jsonb; all_hold boolean; v_outcome text;
begin
  select y.id into v_year
  from academic_year y join school s on s.id = y.school_id
  where s.code = 'DEMO-SSS' and y.status = 'active'
  limit 1;

  if v_year is null then
    select y.id into v_year from academic_year y
    join school s on s.id = y.school_id where s.code = 'DEMO-SSS'
    order by y.starts_on desc limit 1;
  end if;

  for c in select * from promo_parity loop
    v_outcome := null;

    for r in
      select pr.* from promotion_rule pr
      where pr.academic_year_id = v_year
        and pr.is_active
        and pr.grade = (c.facts ->> 'grade')::smallint
        and (pr.stream is null or pr.stream::text = (c.facts ->> 'stream'))
      order by pr.priority
    loop
      all_hold := true;
      for cond in select * from jsonb_array_elements(r.conditions) loop
        if not app.promotion_condition_holds(c.facts, cond) then
          all_hold := false;
          exit;
        end if;
      end loop;

      if all_hold then
        v_outcome := r.outcome::text;
        exit;
      end if;
    end loop;

    -- Same fall-through as app.evaluate_promotion and evaluatePromotion().
    v_outcome := coalesce(v_outcome, 'repeat');

    update promo_parity
       set actual = v_outcome,
           verdict = case when v_outcome = expected then 'ok' else 'MISMATCH' end
     where case_name = c.case_name;
  end loop;
end $$;

select case_name, expected, actual, verdict
from promo_parity order by verdict desc, case_name;

select case
         when exists (select 1 from promo_parity where verdict <> 'ok')
         then 'FAIL — Postgres and TypeScript disagree, see rows above'
         else 'PASS — ' || (select count(*) from promo_parity)::text ||
              ' cases agree across both implementations'
       end as result;
