/**
 * Promotion rules engine — BLUEPRINT §15.4.
 *
 * This is the TypeScript half. The Postgres half is app.promotion_condition_holds
 * and app.evaluate_promotion (migration 56). They must agree, and
 * supabase/tests/promotion_parity.sql checks that they do against a shared
 * fixture table generated by scripts/gen-promotion-parity.mjs.
 *
 * Why two implementations at all: the client needs to show a Rector what would
 * happen if a threshold moved, without a round trip per pupil per keystroke;
 * the database needs to be the authority when the decision is written. The
 * alternative — one implementation in SQL and an approximation in the UI — is
 * how you end up with a screen that disagrees with the record.
 *
 * Facts are computed ONLY in SQL (app.promotion_facts). This module never
 * derives a fact; it evaluates rules against facts it is handed. That is the
 * boundary that makes parity testable at all.
 */

export type PromotionOutcome =
  | 'promote'
  | 'conditional_promote'
  | 'repeat'
  | 'leave'
  | 'refer'

export type Condition =
  | { kind: 'aggregate_gte'; value: number }
  | { kind: 'subject_pass_count_gte'; value: number; level?: 'principal' | 'subsidiary' }
  | { kind: 'credit_count_gte'; value: number; sameSitting?: boolean }
  | { kind: 'attendance_pct_gte'; value: number; countAuthorisedAsPresent?: boolean }
  | { kind: 'times_repeated_lte'; value: number }
  | { kind: 'age_on_date_lte'; value: number; asOf?: 'jan_1' | 'exam_date' }
  | { kind: 'has_medical_certificate_for_prolonged_absence' }
  | { kind: 'core_subject_passed'; subject: 'english' | 'french' | 'maths' }

export interface Rule {
  id: string
  name: string
  grade: number
  stream?: string | null
  outcome: PromotionOutcome
  priority: number
  conditions: Condition[]
  isActive?: boolean
}

/** Exactly the shape app.promotion_facts returns. */
export interface Facts {
  aggregate: number | null
  credit_count: number | null
  pass_count: number | null
  pass_count_principal: number | null
  pass_count_subsidiary: number | null
  attendance_pct: number | null
  attendance_pct_incl_authorised: number | null
  times_repeated: number | null
  age_at_jan_1: number | null
  has_medical_certificate_for_prolonged_absence: boolean | null
  core_passed: Partial<Record<'english' | 'french' | 'maths', boolean>> | null
  grade: number | null
  stream: string | null
}

export interface Verdict {
  outcome: PromotionOutcome
  ruleId: string | null
  ruleName: string
}

/**
 * A missing fact is NOT zero.
 *
 * A pupil with no marks has `aggregate: null`, which must fail `aggregate_gte`
 * rather than be read as 0 and fail it for the wrong reason, or — worse — be
 * read as 0 and pass a `_lte` test. Every comparison below distinguishes the
 * two, and the SQL side does the same with `is not null and`.
 *
 * The exceptions are counts. `credit_count: null` means no results were found,
 * which for a count genuinely does mean zero, and both sides coalesce.
 */
const num = (v: number | null | undefined): number | null =>
  v === null || v === undefined || Number.isNaN(v) ? null : Number(v)

export function conditionHolds(facts: Facts, c: Condition): boolean {
  switch (c.kind) {
    case 'aggregate_gte': {
      const got = num(facts.aggregate)
      return got !== null && got >= c.value
    }

    case 'subject_pass_count_gte': {
      const got =
        c.level === 'principal'
          ? num(facts.pass_count_principal)
          : c.level === 'subsidiary'
            ? num(facts.pass_count_subsidiary)
            : num(facts.pass_count)
      return (got ?? 0) >= c.value
    }

    case 'credit_count_gte':
      // sameSitting is accepted and currently always effectively true: the
      // system records one sitting per year, so credits cannot accumulate
      // across sittings. If resits are ever recorded, both halves must start
      // filtering — change them together.
      return (num(facts.credit_count) ?? 0) >= c.value

    case 'attendance_pct_gte': {
      const got = c.countAuthorisedAsPresent
        ? num(facts.attendance_pct_incl_authorised)
        : num(facts.attendance_pct)
      return got !== null && got >= c.value
    }

    case 'times_repeated_lte':
      return (num(facts.times_repeated) ?? 0) <= c.value

    case 'age_on_date_lte': {
      // Only jan_1 is computed. exam_date needs the exam timetable, and
      // answering it with the wrong date would be worse than refusing.
      if ((c.asOf ?? 'jan_1') !== 'jan_1') return false
      const got = num(facts.age_at_jan_1)
      return got !== null && got <= c.value
    }

    case 'has_medical_certificate_for_prolonged_absence':
      return facts.has_medical_certificate_for_prolonged_absence === true

    case 'core_subject_passed':
      return facts.core_passed?.[c.subject] === true

    default:
      // An unknown condition kind fails. A rule nobody can evaluate must never
      // promote by accident — and this is reachable, because rules are data and
      // a future kind can arrive from the database before this code knows it.
      return false
  }
}

/** ALL conditions must hold. An empty condition list is an unconditional rule. */
export const ruleMatches = (facts: Facts, rule: Rule): boolean =>
  rule.conditions.every((c) => conditionHolds(facts, c))

/**
 * First match by priority wins.
 *
 * Falling through every rule yields `repeat`, matching the SQL. Holding a pupil
 * is the safe direction: it is visible and appealable, whereas a wrongly
 * promoted pupil is discovered a year later by a teacher wondering why they
 * cannot cope.
 */
export function evaluatePromotion(facts: Facts, rules: Rule[]): Verdict {
  const applicable = rules
    .filter((r) => r.isActive !== false)
    .filter((r) => r.grade === facts.grade)
    .filter((r) => r.stream == null || r.stream === facts.stream)
    .sort((a, b) => a.priority - b.priority)

  for (const rule of applicable) {
    if (ruleMatches(facts, rule)) {
      return { outcome: rule.outcome, ruleId: rule.id, ruleName: rule.name }
    }
  }

  return { outcome: 'repeat', ruleId: null, ruleName: 'no rule matched' }
}

/**
 * What would change if a rule were edited? Lets a Rector see the effect of
 * moving a threshold across the whole cohort before saving it, which is the
 * only reason this runs client-side at all.
 */
export function diffCohort(
  cohort: Array<{ studentId: string; facts: Facts }>,
  before: Rule[],
  after: Rule[],
): Array<{ studentId: string; from: PromotionOutcome; to: PromotionOutcome }> {
  const changed = []
  for (const { studentId, facts } of cohort) {
    const a = evaluatePromotion(facts, before).outcome
    const b = evaluatePromotion(facts, after).outcome
    if (a !== b) changed.push({ studentId, from: a, to: b })
  }
  return changed
}
